CREATE DATABASE `cake` /*!40100 DEFAULT CHARACTER SET utf8 */;

CREATE TABLE `cakes` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `name` varchar(100) NOT NULL,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB AUTO_INCREMENT=8 DEFAULT CHARSET=utf8;

INSERT INTO CAKES VALUES (1,"apple");
INSERT INTO CAKES VALUES (2,"chocolate");
INSERT INTO CAKES VALUES (3,"berry");
INSERT INTO CAKES VALUES (4,"vanilla");